name: Update JSON from blizzard.py

on:
  schedule:
    - cron: '*/2 * * * *'  # toutes les 10 minutes (modifie si tu veux plus ou moins)
  workflow_dispatch:         # permet de lancer manuellement

permissions:
  contents: write  # pour pouvoir push

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo (avec token)
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Export API KEY
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Run blizzard.py to generate JSON
      run: python blizzard.py

    - name: Commit and push if data changed
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add leaderboard.json
        git diff --cached --quiet || git commit -m "Auto update leaderboard.json"
        git push origin HEAD:main
